export const LANG: string = window['config'] && window['config'].lang ? window['config'].lang : 'en';

export const CAPTION = {
  ko: {
    ID: '아이디',
    PASSWORD: ' 비밀번호',
    KEEP_ME_SIGNED: '아이디/비밀번호 저장',
    UPDATE: '업데이트',
    LOADING: '로딩중...',
    MY_CLASS: '반 수',
    MY_CLASS_TOTAL: ':',
    STUDENTS: '학생 수',
    HOME: '홈',
    LOGOUT: '로그아웃',
    EXIT: '나가기',
    DATE_FORMAT: 'MM.DD (ddd) HH:mm',
    MON: '월',
    TUE: '화',
    WED: '수',
    THU: '목',
    FRI: '금',
    SAT: '토',
    SUN: '일',
    BOOK_SHELF: '교재 자료',
    SPECIAL_ACTIVITY: '특별 활동',
    LESSON_MAP: '강의 구성', // ui-common.scss 에 적용된 상태
    LOCK: '잠금',
    UNLOCK: '해제',
    PEN_TOOL: '쓰기 도구',
    LIBRARY: '학습 자료',
    TIMER: '타이머',
    PRESENTER_GROUP: '발표자 & 그룹',
    IDEAS_OPINIONS: '아이디어 & 의견',
    PORTFOLIO: '포트폴리오',
    STAMP: '스탬프',
    RESET: '초기화',
    TIMER_STOPWATCH: '타이머 & 스톱워치',
    STOPWATCH: '스톱워치',
    START: '시작',
    STOP: '정지',
    HOUR: '시',
    MINUTE: '분',
    SECOND: '초',
    TIME_OVER: '시간 초과',
    LAP: '랩 타임',
    CHOOSE_PRESENTERS: '발표자 선정',
    CREATE_GROUPS: '그룹 만들기',
    SELECT: '선정',
    RESELECT: '재선정',
    TEACHER: '선생님',
    INCLUDE: '포함',
    GROUP: '그룹',
    LEADER: '리더',
    TOPIC: '주제',
    TOPIC_SENTENCE: '여기를 눌러 주제를 선택하신 후 하단의 녹음하기, 녹화하기를 터치하세요.',
    OK: '확인',
    CANCEL: '취소',
    MVP: '최우수 학생',
    LOGIN: '로그인',
    PARTICIPATE: '참여자',
    ALL: '전체',
    ALL2: '모두',
    DISPLAY_MODE: '이름/별명 선택',
    DISPLAY_MODE_SENTENCE: '이름 또는 별명을 선택하세요.',
    STUDENT_ATTEND: '출석부',
    NAME: '이름',
    NICKNAME: '별명',
    BRAINSTORMING: '브레인스토밍',
    DISCUSSION: '논의',
    DEBATE: '토론',
    POLL: '투표',
    CHATTING: '채팅',
    CHAT: '채팅',
    CHOOSE_TOPIC: '주제 선택',
    STEP1: '1단계',
    STEP2: '2단계',
    STEP3: '3단계',
    WRITE_TOPIC: '주제를 입력하세요.',
    UPLOAD_TIME: '작성 시간',
    AGREE: '동의함',
    DISAGREE: '동의하지 않음',
    READY: '준비중',
    SOON: '수업이 곧 시작됩니다.',
    CHOSEN: '발표자로 선택되었습니다.',
    GROUPS: '당신의 그룹은',
    PLEASE_IDEA: '내용을 입력하세요.',
    RESEND: '재전송',
    CLASS_SETTING: '수업 환경 설정',
    CLASS: '반명',
    LEVEL: '레벨',
    TOTAL: '총 ',
    LESSON_MODE: '수업 모드',
    LEARNING_MODE: '학습 모드',
    BACKGROUND: '배경화면',
    ONLY_TEACH: '선생님만',
    STUDENT_ENGAGEMENT: '선생님+학생',
    UNIT_FOCUS: '학습 개요',
    CLASSROOM: '교실',
    INCLASS: '수업',
    REMOTE: '리모트',
    TEACHER_SETTING: '선생 세팅',
    STUDENT_SETTING: '학생 세팅',
    VIDEO: '비디오',
    AUDIO: '오디오',
    VIDEO_AUDIO: '비디오 & 오디오',
    AUDIO_ONLY: '오디오만',
    VIDEO_SETMSG: '비디오 설정 시, 비디오로 입장이 불가능한 학생은 오디오로 자동 입장됩니다.',
    ONLY_CLASS: '오늘 수업만 적용',
    APPLY: '적용',
    DEVICE_CHECK: '디바이스 설정',
    NOZOOMKEYALERT: 'Remote Class 수업을 위해서는 Zoom meeting information 입력해 주세요!'
  },
  en: {
    ID: 'ID',
    PASSWORD: ' Password',
    KEEP_ME_SIGNED: 'Keep me Signed in',
    UPDATE: 'UPDATE',
    LOADING: 'LOADING...',
    MY_CLASS: 'My Classes',
    MY_CLASS_TOTAL: 'Total',
    STUDENTS: 'Students', // 영문일 경우 글자크기 18pt :  .classwrap .classlist li .cCnt p
    HOME: 'HOME',
    LOGOUT: 'LOGOUT',
    EXIT: 'EXIT',
    DATE_FORMAT: 'ddd MM.DD HH:mm',
    MON: 'Mon',
    TUE: 'Thu',
    WED: 'Wed',
    THU: 'Thu',
    FRI: 'Fri',
    SAT: 'Sat',
    SUN: 'Sun',
    BOOK_SHELF: 'Bookshelf',
    SPECIAL_ACTIVITY: '3-Minute Activity',
    LESSON_MAP: 'Lesson Map',
    LOCK: 'Lock',
    UNLOCK: 'UnLock',
    PEN_TOOL: 'Pen Tool',
    LIBRARY: 'Library',
    TIMER: 'Timer',
    PRESENTER_GROUP: 'Presenters & Groups',
    IDEAS_OPINIONS: 'Ideas & Opinions',
    PORTFOLIO: 'Portfolio',
    STAMP: 'Stamp',
    RESET: 'RESET',
    TIMER_STOPWATCH: 'Timer & Stopwatch',
    STOPWATCH: 'Stopwatch',
    START: 'Start',
    STOP: 'Stop',
    HOUR: 'Hour',
    MINUTE: 'min',
    SECOND: 'sec',
    TIME_OVER: 'Time Over',
    LAP: 'Lap',
    CHOOSE_PRESENTERS: 'Choose Presenters',
    CREATE_GROUPS: 'Create Groups',
    SELECT: 'Select',
    RESELECT: 'Reselect',
    TEACHER: 'Teacher',
    INCLUDE: '',
    GROUP: 'Group',
    LEADER: 'Leader',
    TOPIC: 'Topic',
    TOPIC_SENTENCE: 'Touch the Topic icon above and choose a topic.',
    OK: 'OK',
    CANCEL: 'CANCEL',
    MVP: 'MVP',
    LOGIN: 'LOGIN',
    PARTICIPATE: 'LOGIN',
    ALL: 'ALL',
    ALL2: 'All',
    DISPLAY_MODE: 'Display mode',
    DISPLAY_MODE_SENTENCE: 'Choose a display mode.',
    STUDENT_ATTEND: 'Student attendance',
    NAME: 'Name',
    NICKNAME: 'NickName',
    BRAINSTORMING: 'Brainstorming',
    DISCUSSION: 'Discussion',
    DEBATE: 'Debate',
    POLL: 'Poll',
    CHATTING: 'Chatting',
    CHAT: 'Chat',
    CHOOSE_TOPIC: 'Choose a topic',
    STEP1: 'Step 1',
    STEP2: 'Step 2',
    STEP3: 'Step 3',
    WRITE_TOPIC: 'Write your own topic.',
    UPLOAD_TIME: 'Upload Time',
    AGREE: 'Agree',
    DISAGREE: 'Disagree',
    READY: 'Ready',
    SOON: 'Class will start soon.',
    CHOSEN: `You're chosen.`,
    GROUPS: `You're group`,
    PLEASE_IDEA: 'Please type your idea here',
    RESEND: 'RESEND',
    CLASS_SETTING: 'Class Setting',
    CLASS: 'Class',
    LEVEL: 'Level',
    TOTAL: 'Total ',
    LESSON_MODE: 'Lesson Mode',
    LEARNING_MODE: 'Learning Mode',
    BACKGROUND: 'Background',
    ONLY_TEACH: 'Only Teaching',
    STUDENT_ENGAGEMENT: 'Student Engagement',
    UNIT_FOCUS: 'Unit Focus',
    CLASSROOM: 'Classroom',
    INCLASS: 'In Class',
    REMOTE: 'Remote',
    TEACHER_SETTING: 'Teacher Setting',
    STUDENT_SETTING: 'Student Setting',
    VIDEO: 'Video',
    AUDIO: 'Audio',
    VIDEO_AUDIO: 'Video & Audio',
    AUDIO_ONLY: 'Audio Only',
    VIDEO_SETMSG: 'Even though video is set, to students who are not avaible video, audio is set automatically.',
    ONLY_CLASS: 'Today\'s class only',
    APPLY: 'Apply',
    DEVICE_CHECK: 'Device Check',
    NOZOOMKEYALERT: 'You must enter Zoom meeting information to start a remote class.'
  }
};
